pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        maven {
            url 'https://storage.googleapis.com/download.flutter.io'
        }
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        maven {
            url 'https://storage.googleapis.com/download.flutter.io'
        }
    }
}

setBinding(new Binding([gradle: this]))
//flutter_module工程git地址 https://github.com/zyd806094224/lib_flutter
evaluate(new File('/Users/zhaoyudong/FlutterProjects/lib_flutter/.android/include_flutter.groovy'))

rootProject.name = "AndroidSeedProject"
include ':app'
include ':lib_framework'
include ':lib_network'
include ':lib_common'
include ':lib_room'
include ':mod_main'
include ':lib_html'
include ':lib_glide'
include ':lib_universaldialog'
include ':lib_flutter'
project(':lib_flutter').projectDir = new File('../../FlutterProjects/lib_flutter')
