pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        maven {
            allowInsecureProtocol = true
            url "http://maven.geelib.360.cn/nexus/repository/replugin/"
        }
    }
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == 'com.qihoo360.replugin.replugin-host-gradle') {
                useModule('com.qihoo360.replugin:replugin-host-gradle:' + requested.version)
            }
            if (requested.id.id == 'com.github.dcendents.android-maven-plugin'){
                useModule('com.github.dcendents:android-maven-plugin:' + requested.version)
            }
        }
    }
}
dependencyResolutionManagement {
    //repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS) // AOP
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        maven {
            allowInsecureProtocol = true
            url "http://maven.geelib.360.cn/nexus/repository/replugin/"
        }
    }
}
rootProject.name = "AndroidSeedProject"
include ':app'
include ':lib_framework'
include ':lib_network'
include ':lib_common'
include ':lib_room'
include ':mod_main'
include ':lib_html'
include ':lib_glide'
include ':lib_universaldialog'
