plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-kapt'
}

android {
    namespace 'com.demo.androidseedproject.compose.feature'
    compileSdk rootProject.android.compileSdk

    defaultConfig {
        minSdk rootProject.android.minSdk
        targetSdk rootProject.android.targetSdk

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"

        //ARouter
        kapt {
            arguments {
                arg("AROUTER_MODULE_NAME", project.getName())
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    buildFeatures {
        compose = true
    }
    composeOptions {
        kotlinCompilerExtensionVersion rootProject.dependVersion.composeCompilerVersion
    }
}

dependencies {
    implementation rootProject.depsLibs.coreKtx
    implementation rootProject.depsLibs.appcompat

    // Compose Dependencies
    implementation rootProject.depsLibs.activityCompose
    implementation rootProject.depsLibs.composeUI
    debugImplementation rootProject.depsLibs.composeTooling
    implementation rootProject.depsLibs.composeToolingPreview

    // Compose 布局和动画
    implementation rootProject.depsLibs.composeFoundation
    implementation rootProject.depsLibs.composeFoundationLayout
    implementation rootProject.depsLibs.composeAnimation
    implementation rootProject.depsLibs.composeRuntime

    // Material Icons (需要material图标库来访问扩展图标)
    implementation rootProject.depsLibs.materialIconsCore
    implementation rootProject.depsLibs.materialIconsExtended

    // ViewModel for Compose
    implementation rootProject.depsLibs.viewModelCompose

    // Paging for Compose (上拉加载)
    implementation rootProject.depsLibs.pagingCompose

  
    // Material3
    implementation rootProject.depsLibs.material3

    // ARouter
    implementation rootProject.depsLibs.aroutreApi
    kapt rootProject.depsLibs.arouterCompiler

    // Koin
    implementation rootProject.depsLibs.koinAndroid
    implementation rootProject.depsLibs.koinCompose
}
