plugins {
    alias(libs.plugins.androidLibrary)
    alias(libs.plugins.kotlinAndroid)
    id 'kotlin-kapt'
}

android {
    compileSdk rootProject.android.compileSdk

    defaultConfig {
        minSdk rootProject.android.minSdk
        targetSdk rootProject.android.targetSdk

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {
    compileOnly fileTree(dir: 'libs', include: ['*.jar'])
    compileOnly libs.coreKtx
    compileOnly libs.appcompat
    compileOnly libs.material
    compileOnly libs.constraintlayout

    compileOnly libs.glide
    kapt libs.glideCompiler

    compileOnly project(path: ':lib_framework')
}
