plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'maven-publish'
}

android {
    compileSdk rootProject.android.compileSdk

    defaultConfig {
        minSdk rootProject.android.minSdk
        targetSdk rootProject.android.targetSdk

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                from components.release

                // 这些信息会决定 Package 的名称
                groupId = 'com.github.zyd806094224'  // 使用你的 GitHub 用户名
                artifactId = 'lib-html'       // 库名称
                version = '1.0.8'             // 版本号
            }

            // 快照版本配置
            snapshot(MavenPublication) {
                from components.release

                groupId = 'com.github.zyd806094224'
                artifactId = 'lib-html'
                version = '1.0.8-SNAPSHOT'    // 快照版本号，可以重复发布
            }
        }

        repositories {
            maven {
                name = "GitHubPackages"
                // URL 格式: https://maven.pkg.github.com/用户名/仓库名
                url = uri("https://maven.pkg.github.com/zyd806094224/AndroidMavenPublish")
                credentials {
                    username = project.findProperty("gpr.user") ?: System.getenv("GITHUB_ACTOR")
                    password = project.findProperty("gpr.key") ?: System.getenv("GITHUB_TOKEN")
                }
            }
        }
    }
}


dependencies {
    compileOnly fileTree(dir: 'libs', include: ['*.jar'])
    compileOnly rootProject.depsLibs.coreKtx
    compileOnly rootProject.depsLibs.appcompat
}