plugins {
    alias(libs.plugins.androidLibrary)
    alias(libs.plugins.kotlinAndroid)
    id 'kotlin-parcelize'
    id 'kotlin-kapt'
}

android {
    compileSdk rootProject.android.compileSdk

    defaultConfig {
        minSdk rootProject.android.minSdk
        targetSdk rootProject.android.targetSdk

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"

        //ARouter
        kapt {
            arguments {
                arg("AROUTER_MODULE_NAME", project.getName())
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    buildFeatures {
        dataBinding = true
        viewBinding = true
    }
}

dependencies {
    compileOnly fileTree(dir: 'libs', include: ['*.jar'])
    compileOnly libs.coreKtx
    implementation libs.appcompat
    compileOnly libs.material
    compileOnly libs.constraintlayout

    compileOnly libs.refreshLayout
    compileOnly libs.refreshHeader
    compileOnly libs.refreshFooter

    compileOnly libs.aroutreApi
    kapt libs.arouterCompiler

    compileOnly project(path: ':lib_framework')
    implementation project(path: ':lib_glide')
    compileOnly project(path: ':lib_html')
}
